apiVersion: v1
kind: ConfigMap
metadata:
  name: devboxmonitor-config
  namespace: sealos-system
data:
  config.yml: |
    listenAddress: ":8080"
    metricsHost: "http://victoria-metrics-vmselect.sealos-system.svc.cluster.local:8481/select/0/prometheus"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devboxmonitor
  namespace: sealos-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devboxmonitor
  template:
    metadata:
      labels:
        app: devboxmonitor
    spec:
      containers:
      - name: devboxmonitor
        image: ghcr.io/labring/sealos-devboxmonitor-service:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config
          mountPath: /config
        livenessProbe:
          httpGet:
            path: /livez
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: config
        configMap:
          name: devboxmonitor-config

---
apiVersion: v1
kind: Service
metadata:
  name: devboxmonitor
  namespace: sealos-system
spec:
  selector:
    app: devboxmonitor
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
